// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj2Ksu-W9mPvUj6wE3gFPsvkI3Ws3InOY',
    appId: '1:826148711029:web:135a32f2b46b8d7bbe663c',
    messagingSenderId: '826148711029',
    projectId: 'daominhquanproject20200913',
    authDomain: 'daominhquanproject20200913.firebaseapp.com',
    databaseURL: 'https://daominhquanproject20200913.firebaseio.com',
    storageBucket: 'daominhquanproject20200913.firebasestorage.app',
    measurementId: 'G-T3WGJBEER5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQubu-g9j4fkeXau6DAZnkg7jDn3DkQC8',
    appId: '1:826148711029:android:a994b65877718b72be663c',
    messagingSenderId: '826148711029',
    projectId: 'daominhquanproject20200913',
    databaseURL: 'https://daominhquanproject20200913.firebaseio.com',
    storageBucket: 'daominhquanproject20200913.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9GK9A9nMzKbwtXMxySZfOepqVld_BNC4',
    appId: '1:826148711029:ios:4c2ee520fe8d3deabe663c',
    messagingSenderId: '826148711029',
    projectId: 'daominhquanproject20200913',
    databaseURL: 'https://daominhquanproject20200913.firebaseio.com',
    storageBucket: 'daominhquanproject20200913.firebasestorage.app',
    iosBundleId: 'com.daominhquan.task-manager',
  );
}
